import { readJSON } from '../utils/fse.js'
import { writeFile } from 'fs/promises'
import path from 'path'
import { readTasks } from './tasks.js'
import { getGitState } from './git.js'
import { getGraphifyRef } from './graphify.js'
import { getRecentDecisions } from './decisions.js'
import {
  tasksPath,
  decisionsPath,
  sessionIndexPath,
  handoffPath,
} from '../utils/paths.js'
import { estimateTokens } from '../utils/tokens.js'

interface SessionIndex {
  decisions: string[]
  indexedAt: string
  sessionCount: number
}

/**
 * Layer 6: Handoff brief compiler.
 *
 * Reads all layers in parallel and compiles a structured Markdown file
 * targeting ≤ maxTokens. This is the file every new agent reads at session start.
 *
 * Section tags are machine-readable: [CONTEXT_REF], [NEXT], [IN_PROGRESS],
 * [DONE], [BLOCKED], [DECISIONS], [CHANGED_FILES]
 */
export async function compileHandoffBrief(
  projectRoot: string,
  trailDir: string,
  graphifyPath: string = 'graphify-out/graph.json',
  maxTokens: number = 2000
): Promise<{ brief: string; tokens: number; outputPath: string }> {
  const readSessionIndex = async (): Promise<SessionIndex | null> => {
    try { return await readJSON(sessionIndexPath(trailDir)) }
    catch { return null }
  }

  const [tasks, git, graph, decisions, sessionIndex] = await Promise.all([
    readTasks(tasksPath(trailDir)),
    getGitState(projectRoot),
    getGraphifyRef(projectRoot, graphifyPath),
    getRecentDecisions(decisionsPath(trailDir), 10),
    readSessionIndex(),
  ])

  const done       = tasks.tasks.filter((t) => t.status === 'done')
  const active     = tasks.tasks.filter((t) => t.status === 'in-progress')
  const blocked    = tasks.tasks.filter((t) => t.status === 'blocked')
  const queued     = tasks.tasks.filter((t) => t.status === 'queued')
  const projectName = tasks.projectName || path.basename(projectRoot)

  // ─── Build sections ──────────────────────────────────────────────────────

  const gitLine = git.available
    ? `Branch: \`${git.branch}\` | Last commit: \`${git.lastCommitHash}\` ${git.lastCommitMessage}`
    : 'Git: not available'

  const contextRefLines = graph.available
    ? [
        `- Code graph: \`${graph.graphPath}\` (${graph.nodeCount} nodes, ${graph.edgeCount} edges)`,
        graph.topNodes.length > 0
          ? `- Key nodes: ${graph.topNodes.join(', ')}`
          : '',
      ].filter(Boolean)
    : ['- No Graphify graph found — run `graphify .` to index the codebase']

  const nextTask = active[0] ?? queued[0]
  const nextLines = nextTask
    ? [`- **${nextTask.title}** [${nextTask.status}]${nextTask.notes ? ` — ${nextTask.notes}` : ''}`]
    : ['- All tasks complete ✓']

  const inProgressLines = active.length > 0
    ? active.map((t) => `- ${t.title}${t.notes ? ` — ${t.notes}` : ''}`)
    : ['- none']

  // All queued tasks beyond the first (the backlog)
  const queuedLines = queued.length > 1
    ? queued.slice(1).map((t) => `- ${t.title} [queued]`)
    : []

  const doneLines = done.length > 0
    ? done.slice(-6).map((t) => `- ✓ ${t.title}`)
    : ['- none yet']

  const blockedLines = blocked.length > 0
    ? blocked.map((t) => `- ✗ ${t.title} — **REASON**: ${t.blocked_reason ?? 'unspecified'}`)
    : ['- none']

  const decisionLines = [
    ...decisions,
    ...(sessionIndex?.decisions ?? []).slice(0, 4).map((d: string) => `- [session] ${d}`),
  ]

  const changedFileLines = git.changedFiles.length > 0
    ? git.changedFiles.slice(0, 12).map((f) => `- \`${f}\``)
    : ['- no uncommitted changes']

  // ─── Assemble brief ──────────────────────────────────────────────────────

  const lines = [
    `# grwm Handoff Brief — ${projectName}`,
    `> Generated: ${new Date().toISOString()} | ${gitLine}`,
    `> *Read this file before starting any work in this session.*`,
    '',
    '## [CONTEXT_REF]',
    ...contextRefLines,
    '',
    '## [NEXT]',
    ...nextLines,
    '',
    ...(queuedLines.length > 0 ? ['## [QUEUED]', ...queuedLines, ''] : []),
    '## [IN_PROGRESS]',
    ...inProgressLines,
    '',
    '## [DONE]',
    ...doneLines,
    '',
    '## [BLOCKED]',
    ...blockedLines,
    '',
    '## [DECISIONS]',
    ...(decisionLines.length > 0 ? decisionLines : ['- No decisions logged yet']),
    '',
    '## [CHANGED_FILES]',
    ...changedFileLines,
    '',
    '---',
    `*Generated by [grwm](https://npmjs.com/package/grwm) — the universal AI agent handoff tool.*`,
  ]

  const brief = lines.filter((l) => l !== undefined).join('\n')
  const tokens = estimateTokens(brief)

  const outPath = handoffPath(trailDir)
  await writeFile(outPath, brief, 'utf8')

  return { brief, tokens, outputPath: outPath }
}
